(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const A=()=>window.OscarActivation;let databases=[],companies=[];
const safe=v=>String(v??'').trim(), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10), uid=p=>`${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
function toast(msg,type='ok'){const t=$('#toast');t.textContent=msg;t.className='toast show '+type;clearTimeout(t._timer);t._timer=setTimeout(()=>t.className='toast',3600)}
function master(){const m=A().readMasterConfig();if(!m?.database?.databaseURL||!m?.database?.authToken)throw new Error('أدخل قاعدة البيانات الأم واحفظها أولاً.');return m}
function root(){return master().adminRootPath||'oscar/admin'}
function masterDb(){return master().database}
function modal(id,show=true){$(id).classList.toggle('show',show)}
function fmt(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ar-EG-u-nu-latn',{dateStyle:'medium'}).format(new Date(v))}catch(_){return v}}
function generateKey(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',part=()=>Array.from({length:4},()=>chars[Math.floor(Math.random()*chars.length)]).join('');return`MZ-${part()}-${part()}`}
function resultRows(result){return A().tursoDirect.rows(result)}
async function listRecords(prefix){const rows=await A().tursoDirect.listPrefix(masterDb(),`${root()}/${prefix}`,{ensureSchema:true});return rows.filter(r=>!Number(r.deleted)).map(r=>r.payload).filter(Boolean)}
async function saveMaster(){const url=safe($('#masterUrl').value),token=safe($('#masterToken').value);if(!url||!token)throw new Error('أدخل الرابط والتوكن.');const cfg=A().saveMasterConfig({databaseURL:url,authToken:token,table:'oscar_rtdb'});$('#masterStatus').textContent='جاري اختبار الاتصال...';await A().tursoDirect.ensure(cfg.database);$('#masterStatus').textContent='الاتصال بالقاعدة الأم جاهز ومحفوظ محلياً.';$('#masterStatus').className='status ok';await loadAll()}
async function loadAll(){const m=A().readMasterConfig();if(!m){databases=[];companies=[];render();return}$('#masterUrl').value=m.database.databaseURL||'';$('#masterToken').value=m.database.authToken||'';$('#masterStatus').textContent='تم تحميل قاعدة الأم من التخزين المحلي المشفر.';$('#masterStatus').className='status ok';try{[databases,companies]=await Promise.all([listRecords('databases'),listRecords('companies')]);databases.sort((a,b)=>String(a.name).localeCompare(String(b.name),'ar'));companies.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));render()}catch(e){$('#masterStatus').textContent='تعذر قراءة القاعدة الأم: '+e.message;$('#masterStatus').className='status error';throw e}}
function render(){
 $('#statDatabases').textContent=databases.length;$('#statCompanies').textContent=companies.length;$('#statActive').textContent=companies.filter(x=>x.status==='active').length;$('#statStopped').textContent=companies.filter(x=>x.status!=='active').length;
 const count=id=>companies.filter(c=>c.databaseId===id).length;$('#databasesBody').innerHTML=databases.length?databases.map(d=>`<tr><td><b>${esc(d.name)}</b></td><td class="mono">${esc(d.id)}</td><td>${count(d.id)}</td><td>${fmt(d.updatedAt||d.createdAt)}</td><td><div class="actions"><button class="btn" data-edit-db="${d.id}">تعديل</button><button class="btn danger" data-delete-db="${d.id}" ${count(d.id)?'disabled':''}>حذف</button></div></td></tr>`).join(''):`<tr><td colspan="5" class="empty">لا توجد قواعد محفوظة.</td></tr>`;
 const options='<option value="">كل القواعد</option>'+databases.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join(''),filter=$('#companyDbFilter'),old=filter.value;filter.innerHTML=options;filter.value=old;
 const select=$('#companyForm select[name=databaseId]');select.innerHTML='<option value="">اختر القاعدة...</option>'+databases.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');
 renderCompanies()
}
function renderCompanies(){const filter=$('#companyDbFilter').value,list=companies.filter(c=>!filter||c.databaseId===filter);$('#companiesBody').innerHTML=list.length?list.map(c=>`<tr><td><b>${esc(c.companyName)}</b><br><small>${esc(c.id)}</small></td><td class="mono">${esc(c.companyKey)}</td><td>${esc(c.databaseName||databases.find(d=>d.id===c.databaseId)?.name||'—')}</td><td>${esc(c.manager?.name||'—')}</td><td>${c.plan==='lifetime'?'<span class="badge blue">مدى الحياة</span>':esc(c.plan||'pro')}</td><td><span class="badge ${c.status==='active'?'green':'red'}">${c.status==='active'?'نشط':'موقوف'}</span></td><td>${c.endAt?fmt(c.endAt):'مدى الحياة'}</td><td><button class="btn primary" data-download-company="${c.id}" ${c.status==='active'?'':'disabled'}>تحميل .mzauth</button></td><td><div class="actions"><button class="btn" data-edit-company="${c.id}">تعديل</button><button class="btn" data-renew-company="${c.id}">تجديد الملف</button><button class="btn ${c.status==='active'?'danger':'green'}" data-toggle-company="${c.id}">${c.status==='active'?'إيقاف':'تفعيل'}</button></div></td></tr>`).join(''):`<tr><td colspan="9" class="empty">لا توجد شركات ضمن هذا الاختيار.</td></tr>`}
async function databaseCredentials(id){const d=databases.find(x=>x.id===id);if(!d)throw new Error('قاعدة الشركة غير موجودة في السجل.');const m=master();const secret=m.database.authToken;return{...await A().openObject(d.vault,secret),table:'oscar_rtdb'}}
async function publishCompany(company){const db=await databaseCredentials(company.databaseId),access={companyId:company.id,tenantId:company.id,companyName:company.companyName,companyKey:company.companyKey,status:company.status,plan:company.plan,startAt:company.startAt,endAt:company.endAt||'',manager:company.manager,updatedAt:Date.now()};await A().tursoDirect.writeExact(db,`oscar/companies/${encodeURIComponent(company.id)}/access/company`,access,Date.now(),false);return db}
async function saveCompanyRecord(company){company.updatedAt=new Date().toISOString();await A().tursoDirect.writeExact(masterDb(),`${root()}/companies/${company.id}`,company,Date.now(),false);return company}
async function upsertCompany(fd){const id=safe(fd.get('id'))||uid('CMP'),existing=companies.find(x=>x.id===id),databaseId=safe(fd.get('databaseId')),database=databases.find(x=>x.id===databaseId);if(!database)throw new Error('اختر قاعدة شركة مسجلة.');const key=safe(fd.get('companyKey')).toUpperCase();if(companies.some(x=>x.companyKey===key&&x.id!==id))throw new Error('مفتاح الشركة مستخدم لشركة أخرى.');const manager=existing?.manager?{...existing.manager}:{id:uid('MGR'),role:'مدير النظام',system:true,permissions:['*'],createdAt:new Date().toISOString(),authVersion:uid('AUTH')};manager.name=safe(fd.get('managerName'))||'مدير النظام';manager.displayName=manager.name;manager.active=true;const company={...existing,id,companyName:safe(fd.get('companyName')),companyKey:key,databaseId,databaseName:database.name,plan:safe(fd.get('plan'))||'lifetime',status:safe(fd.get('status'))||'active',startAt:safe(fd.get('startAt'))||today(),endAt:safe(fd.get('endAt')),manager,createdAt:existing?.createdAt||new Date().toISOString()};await publishCompany(company);await saveCompanyRecord(company);await loadAll();return company}
async function downloadCompany(company,rotate=false){if(!company)throw new Error('الشركة غير موجودة.');const db=await databaseCredentials(company.databaseId);try{const remote=await A().tursoDirect.readExact(db,`oscar/companies/${encodeURIComponent(company.id)}/access/company`,{ensureSchema:true}),value=remote&&typeof remote==='object'&&Object.prototype.hasOwnProperty.call(remote,'v')?(remote.deleted?null:remote.v):remote;if(value?.manager?.id&&String(value.manager.id)===String(company.manager?.id||''))company.manager={...company.manager,...value.manager}}catch(_){}if(rotate){company.manager={...company.manager,authVersion:uid('AUTH'),updatedAt:new Date().toISOString()};await publishCompany(company);await saveCompanyRecord(company);await loadAll();company=companies.find(x=>x.id===company.id)}else await saveCompanyRecord(company);const payload={type:'company-manager',activationKey:company.companyKey,fileId:`manager_${company.manager.id}_${company.manager.authVersion}`,companyId:company.id,tenantId:company.id,companyKey:company.companyKey,companyName:company.companyName,status:company.status,plan:company.plan,startAt:company.startAt,expiresAt:company.endAt||'',database:db,rootPath:'oscar/companies',account:{...company.manager,branchId:'BR-MAIN',permissions:[]}};await A().downloadActivationFile(payload,`${company.companyName}-مدير.mzauth`)}
async function saveDatabase(fd){const id=safe(fd.get('id'))||uid('DB'),existing=databases.find(x=>x.id===id),name=safe(fd.get('name')),databaseURL=safe(fd.get('databaseURL')),authToken=safe(fd.get('authToken'));if(!name||!databaseURL||!authToken)throw new Error('أكمل بيانات القاعدة.');const cfg={databaseURL,authToken,table:'oscar_rtdb'};await A().tursoDirect.ensure(cfg);const vault=await A().sealObject({databaseURL,authToken},masterDb().authToken),record={id,name,vault,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};await A().tursoDirect.writeExact(masterDb(),`${root()}/databases/${id}`,record);await loadAll();return record}
function openDatabase(d=null){const f=$('#databaseForm');f.reset();f.elements.id.value=d?.id||'';f.elements.name.value=d?.name||'';if(d){databaseCredentials(d.id).then(cfg=>{f.elements.databaseURL.value=cfg.databaseURL;f.elements.authToken.value=cfg.authToken}).catch(e=>toast(e.message,'error'))}modal('#databaseModal',true)}
function openCompany(c=null){const f=$('#companyForm');f.reset();$('#companyModalTitle').textContent=c?'تعديل الشركة':'شركة جديدة';f.elements.id.value=c?.id||'';f.elements.companyName.value=c?.companyName||'';f.elements.companyKey.value=c?.companyKey||generateKey();f.elements.databaseId.value=c?.databaseId||'';f.elements.managerName.value=c?.manager?.name||'مدير النظام';f.elements.plan.value=c?.plan||'lifetime';f.elements.status.value=c?.status||'active';f.elements.startAt.value=(c?.startAt||today()).slice(0,10);f.elements.endAt.value=(c?.endAt||'').slice(0,10);modal('#companyModal',true)}
async function toggleCompany(id){const c=companies.find(x=>x.id===id);if(!c)return;c.status=c.status==='active'?'stopped':'active';await publishCompany(c);await saveCompanyRecord(c);await loadAll();toast(c.status==='active'?'تم تفعيل الشركة ونشر الحالة.':'تم إيقاف الشركة ونشر الحالة.','ok')}
async function deleteDatabase(id){if(companies.some(c=>c.databaseId===id))throw new Error('لا يمكن حذف قاعدة مرتبطة بشركات.');await A().tursoDirect.writeExact(masterDb(),`${root()}/databases/${id}`,{deleted:true,id},Date.now(),true);await loadAll()}
function bind(){
 $('#saveMaster').onclick=()=>saveMaster().then(()=>toast('تم حفظ قاعدة الأم.')).catch(e=>toast(e.message,'error'));$('#clearMaster').onclick=()=>{A().clearMasterConfig();$('#masterUrl').value='';$('#masterToken').value='';databases=[];companies=[];render();$('#masterStatus').textContent='تم مسح بيانات قاعدة الأم من هذا الجهاز.';$('#masterStatus').className='status'};$('#refreshAll').onclick=()=>loadAll().then(()=>toast('تم تحديث السجل.')).catch(e=>toast(e.message,'error'));$('#addDatabase').onclick=()=>openDatabase();$('#addCompany').onclick=()=>openCompany();$('#companyDbFilter').onchange=renderCompanies;$('#generateCompanyKey').onclick=()=>$('#companyForm').elements.companyKey.value=generateKey();
 $$('[data-close]').forEach(b=>b.onclick=()=>modal('#'+b.closest('.modal-root').id,false));$$('.modal-root').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)modal('#'+m.id,false)}));
 $('#databaseForm').onsubmit=e=>{e.preventDefault();const b=e.submitter;b.disabled=true;saveDatabase(new FormData(e.currentTarget)).then(()=>{modal('#databaseModal',false);toast('تم حفظ قاعدة الشركة وتشفير بياناتها.')}).catch(x=>toast(x.message,'error')).finally(()=>b.disabled=false)};
 $('#companyForm').onsubmit=e=>{e.preventDefault();const b=e.submitter;b.disabled=true;upsertCompany(new FormData(e.currentTarget)).then(()=>{modal('#companyModal',false);toast('تم حفظ الشركة ونشر مفتاحها إلى قاعدة الشركة.')}).catch(x=>toast(x.message,'error')).finally(()=>b.disabled=false)};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const run=promise=>{b.disabled=true;promise.catch(x=>toast(x.message,'error')).finally(()=>b.disabled=false)};if(b.dataset.editDb)openDatabase(databases.find(x=>x.id===b.dataset.editDb));if(b.dataset.deleteDb)run(deleteDatabase(b.dataset.deleteDb));if(b.dataset.editCompany)openCompany(companies.find(x=>x.id===b.dataset.editCompany));if(b.dataset.downloadCompany)run(downloadCompany(companies.find(x=>x.id===b.dataset.downloadCompany),false));if(b.dataset.renewCompany)run(downloadCompany(companies.find(x=>x.id===b.dataset.renewCompany),true));if(b.dataset.toggleCompany)run(toggleCompany(b.dataset.toggleCompany))});
 $$('[data-jump]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth'});$$('[data-jump]').forEach(x=>x.classList.toggle('active',x===b))})
}
document.addEventListener('DOMContentLoaded',()=>{if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js?v=7.9-multicompany-live-v2',{scope:'./',updateViaCache:'none'}).catch(()=>{});bind();const m=A().readMasterConfig();if(m){$('#masterUrl').value=m.database.databaseURL||'';$('#masterToken').value=m.database.authToken||'';loadAll().catch(e=>toast(e.message,'error'))}else render()});
})();
